//! Anonymous, static read access to one trusted Capsule Index.
//!
//! The client has no HTTP implementation. A caller supplies a [`tough::Transport`] to each
//! online operation; the client loads the real TUF repository through
//! [`astrid_capsule_index_tuf`], validates the 256-way identity shard generated by
//! `astrid-index-tool`, and then deserializes and re-proves the content-addressed
//! [`PublicationRecord`]. A small digest-keyed cache stores the signed TUF generation and
//! authenticated shard bytes for explicit offline exact-lock reads; lifecycle status is never
//! taken from mutable plaintext sidecars.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use astrid_capsule_index::{
    ActorId, CanonicalSemVer, Coordinate, Digest, IndexError, IndexEvent, IndexIdentity,
    LifecycleState, LockRecord, MirrorUrl, PublicationKey, PublicationRecord, Resolver,
};
use astrid_capsule_index_tuf::{
    Limits as TufLimits, MemoryTransport, OfflinePolicy, TrustConfig, VerificationMode,
    VerifiedIndex, sparse_object_path_from_digest,
};
use semver::VersionReq;
use serde::{Deserialize, Serialize};
use sha2::{Digest as Sha2Digest, Sha256};
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use thiserror::Error;
use tokio::io::AsyncWriteExt;
use url::Url;

/// The number of identity shards emitted by the static Index generator.
pub const IDENTITY_SHARD_COUNT: usize = 256;
/// The exact shard wire schema emitted by `astrid-index-tool`.
pub const IDENTITY_SHARD_SCHEMA: &str = "astrid.capsule-index.identity-shard.v1";

/// Bounds applied to identity-shard, publication-record, and cache reads.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub struct ClientLimits {
    /// Maximum bytes accepted for one identity shard target.
    pub max_shard_bytes: u64,
    /// Maximum bytes accepted for one publication-record target.
    pub max_record_bytes: u64,
    /// Maximum bytes accepted for one cache entry.
    pub max_cache_entry_bytes: u64,
    /// Maximum aggregate bytes fetched from all shards during one range resolve.
    pub max_shard_set_bytes: u64,
}

impl Default for ClientLimits {
    fn default() -> Self {
        Self {
            max_shard_bytes: 1024 * 1024,
            max_record_bytes: 64 * 1024 * 1024,
            max_cache_entry_bytes: 64 * 1024 * 1024,
            max_shard_set_bytes: 16 * 1024 * 1024,
        }
    }
}

/// Configuration for one anonymous client bound to one explicit Index identity.
#[derive(Debug, Clone)]
pub struct ClientConfig {
    /// TUF root, metadata/target bases, and trusted-state policy.
    pub trust: TrustConfig,
    /// Digest-keyed cache directory.
    pub cache_root: PathBuf,
    /// Client-side object and shard bounds.
    pub limits: ClientLimits,
}

impl ClientConfig {
    /// Create a client configuration.
    #[must_use]
    pub fn new(trust: TrustConfig, cache_root: impl Into<PathBuf>) -> Self {
        Self {
            trust,
            cache_root: cache_root.into(),
            limits: ClientLimits::default(),
        }
    }

    /// Replace client-side limits.
    #[must_use]
    pub fn limits(mut self, limits: ClientLimits) -> Self {
        self.limits = limits;
        self
    }
}

/// Lifecycle status carried by an authoritative identity-shard entry.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum ShardStatus {
    /// Eligible for new resolution.
    Active,
    /// Excluded from new resolution but usable by an existing lock.
    Yanked,
    /// Discouraged but still eligible for new resolution.
    Deprecated,
    /// Blocked, including existing locks.
    Revoked,
    /// Removed from ordinary discovery and lock use.
    Tombstoned,
}

impl ShardStatus {
    fn parse(value: &str) -> Result<Self, Error> {
        match value {
            "active" => Ok(Self::Active),
            "yanked" => Ok(Self::Yanked),
            "deprecated" => Ok(Self::Deprecated),
            "revoked" => Ok(Self::Revoked),
            "tombstoned" => Ok(Self::Tombstoned),
            _ => Err(Error::ShardInvalid {
                detail: format!("unknown lifecycle status {value:?}"),
            }),
        }
    }
}

/// One validated authoritative entry in an identity shard.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IdentityShardEntry {
    /// Full identity string (`@namespace/name@version`).
    pub identity: String,
    /// Coordinate without the version.
    pub coordinate: Coordinate,
    /// Canonical release version.
    pub version: CanonicalSemVer,
    /// Immutable publication-record digest.
    pub release_digest: Digest,
    /// Object target path emitted by the static generator.
    pub object: String,
    /// Lifecycle status derived by the generator.
    pub status: ShardStatus,
    /// Whether this entry is authoritative for resolution.
    pub authoritative: bool,
    /// Sealed artifact locations plus any authorized mirror additions, in canonical order.
    pub artifact_locations: Vec<MirrorUrl>,
}

/// A validated 256-way identity shard.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IdentityShard {
    /// Numeric shard selected by the first byte of BLAKE3(identity).
    pub shard: u8,
    entries: Vec<IdentityShardEntry>,
}

impl IdentityShard {
    /// Parse and validate the canonical shard wire emitted by `astrid-index-tool`.
    ///
    /// Validation covers the exact schema, two-digit shard number, identity/coordinate/version
    /// agreement, authoritative entries, duplicate identities, lifecycle vocabulary, and the
    /// digest-derived object path. TUF authenticates the bytes before this parser is called.
    ///
    /// # Errors
    ///
    /// Returns a structured error when the shard exceeds its bound, is malformed, contains an
    /// unauthoritative or duplicate entry, or violates digest/object/mirror bindings.
    pub fn parse(bytes: &[u8], max_bytes: u64) -> Result<Self, Error> {
        if bytes.len() as u64 > max_bytes {
            return Err(Error::ShardTooLarge {
                size: bytes.len() as u64,
                limit: max_bytes,
            });
        }
        let wire: ShardWire =
            serde_json::from_slice(bytes).map_err(|source| Error::ShardJson { source })?;
        if wire.schema != IDENTITY_SHARD_SCHEMA {
            return Err(Error::ShardInvalid {
                detail: format!("unexpected schema {:?}", wire.schema),
            });
        }
        let shard = parse_shard_number(&wire.shard)?;
        let mut seen = BTreeSet::new();
        let mut entries = Vec::with_capacity(wire.entries.len());
        for entry in wire.entries {
            if !entry.authoritative {
                return Err(Error::ShardInvalid {
                    detail: format!("entry {:?} is not authoritative", entry.identity),
                });
            }
            let version: CanonicalSemVer = entry
                .version
                .parse()
                .map_err(|source: IndexError| Error::Protocol(source))?;
            let coordinate: Coordinate = format!("@{}/{}", entry.namespace, entry.name)
                .parse()
                .map_err(|source: IndexError| Error::Protocol(source))?;
            let expected_identity = format!("{coordinate}@{version}");
            if entry.identity != expected_identity {
                return Err(Error::ShardInvalid {
                    detail: format!(
                        "identity {:?} does not match {:?}",
                        entry.identity, expected_identity
                    ),
                });
            }
            if shard_for_identity(&entry.identity) != shard {
                return Err(Error::ShardInvalid {
                    detail: format!("identity {:?} is in the wrong shard", entry.identity),
                });
            }
            if !seen.insert(entry.identity.clone()) {
                return Err(Error::ShardInvalid {
                    detail: format!("duplicate identity {:?}", entry.identity),
                });
            }
            let release_digest = entry
                .release_digest
                .parse()
                .map_err(|source: IndexError| Error::Protocol(source))?;
            let sparse_path = sparse_object_path_from_digest(&release_digest);
            let expected_object = format!("v1/{sparse_path}");
            if entry.object != sparse_path && entry.object != expected_object {
                return Err(Error::ObjectPathMismatch {
                    digest: release_digest.to_string(),
                    expected: expected_object,
                    actual: entry.object,
                });
            }
            let status = ShardStatus::parse(&entry.status)?;
            let mut artifact_locations = Vec::with_capacity(entry.artifact_locations.len());
            for location in entry.artifact_locations {
                let parsed = MirrorUrl::new(location.clone()).map_err(Error::Protocol)?;
                if parsed.as_str() != location {
                    return Err(Error::ShardInvalid {
                        detail: format!("artifact location {location:?} is not canonical"),
                    });
                }
                artifact_locations.push(parsed);
            }
            if artifact_locations.is_empty() {
                return Err(Error::ShardInvalid {
                    detail: "artifact_locations must not be empty".to_owned(),
                });
            }
            if artifact_locations.windows(2).any(|pair| pair[0] >= pair[1]) {
                return Err(Error::ShardInvalid {
                    detail: "artifact_locations must be sorted and unique".to_owned(),
                });
            }
            entries.push(IdentityShardEntry {
                identity: entry.identity,
                coordinate,
                version,
                release_digest,
                object: entry.object,
                status,
                authoritative: entry.authoritative,
                artifact_locations,
            });
        }
        Ok(Self { shard, entries })
    }

    /// Return validated shard entries.
    #[must_use]
    pub fn entries(&self) -> &[IdentityShardEntry] {
        &self.entries
    }
}

/// A publication selected by the protocol resolver.
#[derive(Clone, Debug)]
pub struct ResolvedPublication {
    /// Immutable publication record.
    pub record: PublicationRecord,
    /// Lifecycle state used by the resolver.
    pub state: LifecycleState,
    /// Effective HTTPS artifact locations validated against the sealed record.
    pub artifact_locations: Vec<MirrorUrl>,
}

#[derive(Clone, Debug)]
struct LoadedEntry {
    entry: IdentityShardEntry,
    shard_bytes: Arc<Vec<u8>>,
}

#[derive(Debug)]
struct CachedEntry {
    record_bytes: Vec<u8>,
    shard_bytes: Vec<u8>,
    root_bytes: Vec<u8>,
    root_chain: Vec<(u64, Vec<u8>)>,
    timestamp_bytes: Vec<u8>,
    snapshot_bytes: Vec<u8>,
    targets_bytes: Vec<u8>,
    snapshot_version: u64,
    targets_version: u64,
}

/// Anonymous static read client for one explicit trusted Index.
#[derive(Debug, Clone)]
pub struct IndexClient {
    config: ClientConfig,
}

impl IndexClient {
    /// Construct a client. The TUF configuration already verifies that its shipped root bytes
    /// match the explicit [`IndexIdentity`] fingerprint.
    #[must_use]
    pub fn new(config: ClientConfig) -> Self {
        Self { config }
    }

    /// Return the one Index identity this client may read.
    #[must_use]
    pub fn identity(&self) -> &IndexIdentity {
        &self.config.trust.index_identity
    }

    /// Resolve stable publications for a coordinate and `SemVer` requirement.
    ///
    /// # Errors
    ///
    /// Returns a TUF, shard, object, binding, cache, or protocol resolver error.
    pub async fn resolve<T>(
        &self,
        transport: T,
        coordinate: &Coordinate,
        requirement: &VersionReq,
    ) -> Result<ResolvedPublication, Error>
    where
        T: tough::Transport + Clone + Send + Sync + 'static,
    {
        self.resolve_inner(transport, coordinate, requirement, false, None)
            .await
    }

    /// Resolve while explicitly opting into prerelease candidates.
    ///
    /// # Errors
    ///
    /// Returns a TUF, shard, object, binding, cache, or protocol resolver error.
    pub async fn resolve_prerelease<T>(
        &self,
        transport: T,
        coordinate: &Coordinate,
        requirement: &VersionReq,
    ) -> Result<ResolvedPublication, Error>
    where
        T: tough::Transport + Clone + Send + Sync + 'static,
    {
        self.resolve_inner(transport, coordinate, requirement, true, None)
            .await
    }

    /// Resolve one exact version without any source fallback.
    ///
    /// # Errors
    ///
    /// Returns a TUF, shard, object, binding, cache, or protocol resolver error.
    pub async fn resolve_exact<T>(
        &self,
        transport: T,
        coordinate: &Coordinate,
        version: &CanonicalSemVer,
    ) -> Result<ResolvedPublication, Error>
    where
        T: tough::Transport + Clone + Send + Sync + 'static,
    {
        let requirement =
            VersionReq::parse(&format!("={version}")).map_err(|source| Error::Requirement {
                detail: source.to_string(),
            })?;
        self.resolve_inner(transport, coordinate, &requirement, true, None)
            .await
    }

    /// Resolve while preserving an existing lock. A yanked lock remains usable; a revoked lock
    /// fails through the protocol [`Resolver`].
    ///
    /// # Errors
    ///
    /// Returns a TUF, shard, object, binding, cache, or protocol resolver error.
    pub async fn resolve_with_lock<T>(
        &self,
        transport: T,
        coordinate: &Coordinate,
        requirement: &VersionReq,
        lock: &LockRecord,
    ) -> Result<ResolvedPublication, Error>
    where
        T: tough::Transport + Clone + Send + Sync + 'static,
    {
        self.resolve_inner(transport, coordinate, requirement, true, Some(lock))
            .await
    }

    /// Resolve an exact lock from the local digest cache without network access.
    ///
    /// `AllowExpired` is required because an offline cache cannot establish fresh TUF expiry.
    /// `RejectExpired` therefore fails closed instead of silently weakening the policy.
    ///
    /// # Errors
    ///
    /// Returns an error when the lock is not bound to this Index, the authenticated witness is
    /// incomplete or tampered with, TUF verification fails, or the protocol rejects the lock.
    #[allow(
        clippy::too_many_lines,
        reason = "Offline reconstruction keeps all witness steps together"
    )]
    pub async fn resolve_locked_offline(
        &self,
        lock: &LockRecord,
        policy: OfflinePolicy,
    ) -> Result<ResolvedPublication, Error> {
        if policy == OfflinePolicy::RejectExpired {
            return Err(Error::OfflineExpiryRequired);
        }
        if lock.index_id() != &self.identity().id
            || lock.trust_root() != &self.identity().trust_root
        {
            return Err(Error::Protocol(IndexError::LockIndexMismatch));
        }
        let cache = Cache::new(
            &self.config.cache_root,
            self.config.limits,
            self.config.trust.limits,
        );
        let cached = cache.read(lock.publication_digest()).await?;
        let offline_base = Url::parse("memory://astrid-index-offline/v1/").map_err(|source| {
            Error::CacheCorrupt {
                digest: lock.publication_digest().to_string(),
                detail: source.to_string(),
            }
        })?;
        let root = parse_cached_root(&cached.root_bytes, lock.publication_digest())?;
        let pinned_root = serde_json::from_slice::<tough::schema::Signed<tough::schema::Root>>(
            &self.config.trust.root_bytes,
        )
        .map_err(|source| Error::CacheCorrupt {
            digest: lock.publication_digest().to_string(),
            detail: format!("pinned root is not valid JSON: {source}"),
        })?;
        if root.signed.version < pinned_root.signed.version {
            return Err(Error::CacheCorrupt {
                digest: lock.publication_digest().to_string(),
                detail: format!(
                    "cached root version {} is older than pinned root {}",
                    root.signed.version, pinned_root.signed.version
                ),
            });
        }
        if root.signed.version == pinned_root.signed.version && root != pinned_root {
            return Err(Error::CacheCorrupt {
                digest: lock.publication_digest().to_string(),
                detail: "cached bootstrap root differs from the shipped root".to_owned(),
            });
        }
        let transport = MemoryTransport::new();
        transport
            .insert_path(
                &offline_base,
                "timestamp.json",
                cached.timestamp_bytes.clone(),
            )
            .map_err(Error::Tuf)?;
        transport
            .insert_path(
                &offline_base,
                &format!("{}.snapshot.json", cached.snapshot_version),
                cached.snapshot_bytes.clone(),
            )
            .map_err(Error::Tuf)?;
        transport
            .insert_path(
                &offline_base,
                &format!("{}.targets.json", cached.targets_version),
                cached.targets_bytes.clone(),
            )
            .map_err(Error::Tuf)?;
        let chain = &cached.root_chain;
        let Some((bootstrap_version, bootstrap_bytes)) = chain.first() else {
            return Err(Error::CacheWitnessMissing {
                digest: lock.publication_digest().to_string(),
                detail: "root rotation chain",
            });
        };
        if *bootstrap_version != pinned_root.signed.version.get()
            || bootstrap_bytes.as_slice() != self.config.trust.root_bytes.as_slice()
        {
            return Err(Error::CacheCorrupt {
                digest: lock.publication_digest().to_string(),
                detail: "cached root chain does not start at the shipped root".to_owned(),
            });
        }
        for pair in chain.windows(2) {
            if pair[1].0 != pair[0].0.saturating_add(1) {
                return Err(Error::CacheCorrupt {
                    digest: lock.publication_digest().to_string(),
                    detail: format!(
                        "cached root chain skips version {} before {}",
                        pair[0].0.saturating_add(1),
                        pair[1].0
                    ),
                });
            }
        }
        let Some((final_version, final_bytes)) = chain.last() else {
            unreachable!("chain.first above guarantees a final root");
        };
        if *final_version != root.signed.version.get()
            || final_bytes.as_slice() != cached.root_bytes.as_slice()
        {
            return Err(Error::CacheCorrupt {
                digest: lock.publication_digest().to_string(),
                detail: "cached final root does not match its rotation chain".to_owned(),
            });
        }
        for (version, bytes) in chain.iter().skip(1) {
            transport
                .insert_path(
                    &offline_base,
                    &format!("{version}.root.json"),
                    bytes.clone(),
                )
                .map_err(Error::Tuf)?;
        }
        let object_path = sparse_object_path_from_digest(lock.publication_digest());
        let object_sha = hex::encode(Sha256::digest(&cached.record_bytes));
        transport
            .insert_path(
                &offline_base,
                &format!("{object_sha}.{object_path}"),
                cached.record_bytes.clone(),
            )
            .map_err(Error::Tuf)?;
        let identity = format!("{}@{}", lock.coordinate(), lock.version());
        let shard = shard_for_identity(&identity);
        let shard_path = format!("shards/{shard:02x}.json");
        let shard_sha = hex::encode(Sha256::digest(&cached.shard_bytes));
        transport
            .insert_path(
                &offline_base,
                &format!("{shard_sha}.{shard_path}"),
                cached.shard_bytes.clone(),
            )
            .map_err(Error::Tuf)?;
        let mut trust = self.config.trust.clone();
        trust.metadata_base_url = offline_base.clone();
        trust.targets_base_url = offline_base;
        trust.mode = VerificationMode::Offline(policy);
        trust.datastore_path = cache
            .witness_dir(lock.publication_digest())
            .join("offline-datastore");
        let verified = astrid_capsule_index_tuf::load(trust, transport)
            .await
            .map_err(Error::Tuf)?;
        let shard_bytes = verified
            .read_target(&shard_path)
            .await
            .map_err(Error::Tuf)?;
        let parsed = IdentityShard::parse(&shard_bytes, self.config.limits.max_shard_bytes)?;
        let entry = parsed
            .entries()
            .iter()
            .find(|entry| {
                entry.coordinate == *lock.coordinate()
                    && entry.version == *lock.version()
                    && entry.release_digest == *lock.publication_digest()
            })
            .cloned()
            .ok_or_else(|| {
                Error::Protocol(IndexError::LockMismatch(Box::new(PublicationKey::new(
                    lock.index_id().clone(),
                    lock.coordinate().clone(),
                    lock.version().clone(),
                ))))
            })?;
        let bytes = verified
            .read_sparse_object(
                lock.publication_digest().algorithm().as_str(),
                &lock.publication_digest().hex(),
            )
            .await
            .map_err(|source| map_object_error(source, lock.publication_digest()))?;
        if bytes != cached.record_bytes {
            return Err(Error::CacheCorrupt {
                digest: lock.publication_digest().to_string(),
                detail: "verified object differs from cached record bytes".to_owned(),
            });
        }
        let record: PublicationRecord =
            serde_json::from_slice(&bytes).map_err(|source| Error::RecordJson { source })?;
        prove_record(self.identity(), &entry, &record)?;
        let events = vec![status_event(entry.status, record.key())?];
        let records = vec![record];
        let resolver = Resolver::new(self.identity().clone(), &records, &events);
        let locked = resolver.resolve_locked(lock).map_err(Error::Protocol)?;
        Ok(ResolvedPublication {
            record: locked.record.clone(),
            state: locked.state,
            artifact_locations: entry.artifact_locations,
        })
    }

    async fn resolve_inner<T>(
        &self,
        transport: T,
        coordinate: &Coordinate,
        requirement: &VersionReq,
        explicit_prerelease: bool,
        lock: Option<&LockRecord>,
    ) -> Result<ResolvedPublication, Error>
    where
        T: tough::Transport + Clone + Send + Sync + 'static,
    {
        if let Some(lock) = lock
            && (lock.index_id() != &self.identity().id
                || lock.trust_root() != &self.identity().trust_root)
        {
            return Err(Error::Protocol(IndexError::LockIndexMismatch));
        }
        let verified = astrid_capsule_index_tuf::load(self.config.trust.clone(), transport)
            .await
            .map_err(Error::Tuf)?;
        let entries = self.load_entries(&verified, coordinate, lock).await?;
        let mut records = Vec::with_capacity(entries.len());
        let mut events = Vec::with_capacity(entries.len());
        let cache = Cache::new(
            &self.config.cache_root,
            self.config.limits,
            self.config.trust.limits,
        );
        for loaded in &entries {
            let entry = &loaded.entry;
            let bytes = verified
                .read_sparse_object(
                    entry.release_digest.algorithm().as_str(),
                    &entry.release_digest.hex(),
                )
                .await
                .map_err(|source| map_object_error(source, &entry.release_digest))?;
            if bytes.len() as u64 > self.config.limits.max_record_bytes {
                return Err(Error::RecordTooLarge {
                    digest: entry.release_digest.to_string(),
                    size: bytes.len() as u64,
                    limit: self.config.limits.max_record_bytes,
                });
            }
            let record: PublicationRecord =
                serde_json::from_slice(&bytes).map_err(|source| Error::RecordJson { source })?;
            prove_record(self.identity(), entry, &record)?;
            cache
                .write(
                    &entry.release_digest,
                    &bytes,
                    &verified,
                    loaded.shard_bytes.as_slice(),
                )
                .await?;
            events.push(status_event(entry.status, record.key())?);
            records.push(record);
        }
        let resolver = Resolver::new(self.identity().clone(), &records, &events);
        let selected = if let Some(lock) = lock {
            resolver
                .resolve_with_lock(coordinate, requirement, lock)
                .map_err(Error::Protocol)?
        } else if explicit_prerelease {
            resolver
                .resolve_prerelease(coordinate, requirement)
                .map_err(Error::Protocol)?
        } else {
            resolver
                .resolve(coordinate, requirement)
                .map_err(Error::Protocol)?
        };
        Ok(ResolvedPublication {
            record: selected.record.clone(),
            state: selected.state,
            artifact_locations: entries
                .iter()
                .find(|loaded| loaded.entry.release_digest == *selected.record.publication_digest())
                .map(|loaded| loaded.entry.artifact_locations.clone())
                .ok_or_else(|| Error::CacheCorrupt {
                    digest: selected.record.publication_digest().to_string(),
                    detail: "resolved record has no validated shard entry".to_owned(),
                })?,
        })
    }

    async fn load_entries(
        &self,
        verified: &VerifiedIndex,
        coordinate: &Coordinate,
        lock: Option<&LockRecord>,
    ) -> Result<Vec<LoadedEntry>, Error> {
        let mut entries = Vec::new();
        let mut total = 0u64;
        let shard_numbers: Vec<usize> = if let Some(lock) = lock {
            let version = lock.version().to_string();
            let identity = format!("{coordinate}@{version}");
            vec![usize::from(shard_for_identity(&identity))]
        } else {
            (0..IDENTITY_SHARD_COUNT).collect()
        };
        for shard in shard_numbers {
            let target = format!("shards/{shard:02x}.json");
            let bytes = verified.read_target(&target).await.map_err(Error::Tuf)?;
            total = total.saturating_add(bytes.len() as u64);
            if total > self.config.limits.max_shard_set_bytes {
                return Err(Error::ShardSetTooLarge {
                    size: total,
                    limit: self.config.limits.max_shard_set_bytes,
                });
            }
            let parsed = IdentityShard::parse(&bytes, self.config.limits.max_shard_bytes)?;
            if parsed.shard as usize != shard {
                return Err(Error::ShardMismatch {
                    expected: u8::try_from(shard).map_err(|_| Error::ShardInvalid {
                        detail: format!("shard number {shard} is outside u8 range"),
                    })?,
                    actual: parsed.shard,
                });
            }
            let shard_bytes = Arc::new(bytes);
            entries.extend(
                parsed
                    .entries()
                    .iter()
                    .filter(|entry| &entry.coordinate == coordinate)
                    .cloned()
                    .map(|entry| LoadedEntry {
                        entry,
                        shard_bytes: shard_bytes.clone(),
                    }),
            );
        }
        if let Some(lock) = lock {
            entries.retain(|entry| {
                &entry.entry.version == lock.version()
                    && &entry.entry.release_digest == lock.publication_digest()
            });
        }
        Ok(entries)
    }
}

fn parse_shard_number(value: &str) -> Result<u8, Error> {
    if value.len() != 2 || !value.as_bytes().iter().all(u8::is_ascii_hexdigit) {
        return Err(Error::ShardInvalid {
            detail: format!("shard must be two lowercase hex digits, got {value:?}"),
        });
    }
    if value
        .chars()
        .any(|character| character.is_ascii_uppercase())
    {
        return Err(Error::ShardInvalid {
            detail: format!("shard must be lowercase, got {value:?}"),
        });
    }
    u8::from_str_radix(value, 16).map_err(|source| Error::ShardInvalid {
        detail: source.to_string(),
    })
}

fn shard_for_identity(identity: &str) -> u8 {
    blake3::hash(identity.as_bytes()).as_bytes()[0]
}

fn prove_record(
    identity: &IndexIdentity,
    entry: &IdentityShardEntry,
    record: &PublicationRecord,
) -> Result<(), Error> {
    if record.index_id() != &identity.id {
        return Err(Error::RecordIdentityMismatch {
            expected: identity.id.to_string(),
            actual: record.index_id().to_string(),
        });
    }
    if record.coordinate() != &entry.coordinate {
        return Err(Error::RecordMismatch {
            field: "coordinate",
        });
    }
    if record.version() != &entry.version {
        return Err(Error::RecordMismatch { field: "version" });
    }
    if record.publication_digest() != &entry.release_digest {
        return Err(Error::RecordDigestMismatch {
            expected: entry.release_digest.to_string(),
            actual: record.publication_digest().to_string(),
        });
    }
    if !record
        .artifact()
        .locations()
        .iter()
        .all(|location| entry.artifact_locations.contains(location))
    {
        return Err(Error::ArtifactLocationsMismatch {
            detail: "shard artifact_locations omit a sealed publication location".to_owned(),
        });
    }
    Ok(())
}

fn status_event(status: ShardStatus, key: PublicationKey) -> Result<IndexEvent, Error> {
    let actor = ActorId::new("astrid-index-shard").map_err(Error::Protocol)?;
    Ok(match status {
        ShardStatus::Active => {
            IndexEvent::annotation(actor, key, "status".to_owned(), "active".to_owned())
        },
        ShardStatus::Yanked => IndexEvent::yank(actor, key, None),
        ShardStatus::Deprecated => IndexEvent::deprecate(actor, key, None, None),
        ShardStatus::Revoked => {
            IndexEvent::revoke(actor, key, "revoked by authoritative shard".to_owned())
        },
        ShardStatus::Tombstoned => {
            IndexEvent::tombstone(actor, key, "tombstoned by authoritative shard".to_owned())
        },
    })
}

fn map_object_error(error: astrid_capsule_index_tuf::Error, digest: &Digest) -> Error {
    match error {
        astrid_capsule_index_tuf::Error::MissingTarget { .. }
        | astrid_capsule_index_tuf::Error::Transport {
            kind: tough::TransportErrorKind::FileNotFound,
            ..
        } => Error::MissingObject {
            digest: digest.to_string(),
        },
        other => Error::Tuf(other),
    }
}

fn parse_cached_root(
    bytes: &[u8],
    digest: &Digest,
) -> Result<tough::schema::Signed<tough::schema::Root>, Error> {
    serde_json::from_slice(bytes).map_err(|source| Error::CacheCorrupt {
        digest: digest.to_string(),
        detail: format!("root witness is invalid: {source}"),
    })
}

#[derive(Deserialize)]
struct ShardWire {
    schema: String,
    shard: String,
    entries: Vec<ShardEntryWire>,
}

#[derive(Deserialize)]
struct ShardEntryWire {
    identity: String,
    namespace: String,
    name: String,
    version: String,
    release_digest: String,
    object: String,
    status: String,
    authoritative: bool,
    artifact_locations: Vec<String>,
}

/// Errors returned by the anonymous read client.
#[derive(Debug, Error)]
pub enum Error {
    /// A TUF trust, target, expiry, rollback, or transport failure.
    #[error("TUF verification failed: {0}")]
    Tuf(#[source] astrid_capsule_index_tuf::Error),
    /// A protocol-domain validation or resolver failure.
    #[error("Index protocol error: {0}")]
    Protocol(#[source] IndexError),
    /// The shard JSON was syntactically invalid.
    #[error("identity shard JSON is invalid: {source}")]
    ShardJson {
        /// JSON parser error.
        #[source]
        source: serde_json::Error,
    },
    /// A shard failed semantic validation.
    #[error("identity shard is invalid: {detail}")]
    ShardInvalid {
        /// Validation detail.
        detail: String,
    },
    /// A shard exceeded its configured bound.
    #[error("identity shard is {size} bytes, exceeding limit {limit}")]
    ShardTooLarge {
        /// Observed size.
        size: u64,
        /// Configured bound.
        limit: u64,
    },
    /// Aggregate shard fanout exceeded its configured bound.
    #[error("identity shard set is {size} bytes, exceeding limit {limit}")]
    ShardSetTooLarge {
        /// Observed aggregate size.
        size: u64,
        /// Configured aggregate bound.
        limit: u64,
    },
    /// An entry was found under a different numeric shard.
    #[error("identity shard mismatch: expected {expected:02x}, got {actual:02x}")]
    ShardMismatch {
        /// Requested shard number.
        expected: u8,
        /// Wire shard number.
        actual: u8,
    },
    /// A digest's object path did not match the static generator convention.
    #[error("object path mismatch for {digest}: expected {expected}, got {actual}")]
    ObjectPathMismatch {
        /// Publication digest.
        digest: String,
        /// Expected v1 path.
        expected: String,
        /// Path in the shard wire.
        actual: String,
    },
    /// A publication record embedded another Index identity.
    #[error("publication record Index mismatch: expected {expected}, got {actual}")]
    RecordIdentityMismatch {
        /// Configured Index ID.
        expected: String,
        /// Record Index ID.
        actual: String,
    },
    /// A publication record did not match its shard entry.
    #[error("publication record {field} does not match its shard entry")]
    RecordMismatch {
        /// Mismatched field.
        field: &'static str,
    },
    /// A publication digest did not match its shard entry.
    #[error("publication digest mismatch: expected {expected}, got {actual}")]
    RecordDigestMismatch {
        /// Digest in the shard.
        expected: String,
        /// Digest recomputed by protocol deserialization.
        actual: String,
    },
    /// The signed shard did not preserve all immutable record artifact locations.
    #[error("artifact locations are inconsistent: {detail}")]
    ArtifactLocationsMismatch {
        /// Validation detail.
        detail: String,
    },
    /// A publication-record target exceeded the client bound.
    #[error("publication record {digest} is {size} bytes, exceeding limit {limit}")]
    RecordTooLarge {
        /// Publication digest.
        digest: String,
        /// Observed size.
        size: u64,
        /// Configured bound.
        limit: u64,
    },
    /// A publication-record target was syntactically invalid.
    #[error("publication record JSON is invalid: {source}")]
    RecordJson {
        /// JSON parser or protocol-deserialization error.
        #[source]
        source: serde_json::Error,
    },
    /// The target for a validated publication digest was absent.
    #[error("publication object {digest} is missing")]
    MissingObject {
        /// Publication digest.
        digest: String,
    },
    /// Cache bytes were absent.
    #[error("cache entry {digest} is missing")]
    CacheMiss {
        /// Publication digest.
        digest: String,
    },
    /// Cache bytes exceeded the configured bound.
    #[error("cache entry {digest} is {size} bytes, exceeding limit {limit}")]
    CacheTooLarge {
        /// Publication digest.
        digest: String,
        /// Observed size.
        size: u64,
        /// Configured bound.
        limit: u64,
    },
    /// Cache bytes or authenticated TUF witness were malformed or inconsistent.
    #[error("cache entry {digest} is corrupt: {detail}")]
    CacheCorrupt {
        /// Publication digest.
        digest: String,
        /// Corruption detail.
        detail: String,
    },
    /// Signed TUF metadata or shard witness bytes were missing, so offline verification cannot proceed.
    #[error("cache entry {digest} has no authenticated witness: {detail}")]
    CacheWitnessMissing {
        /// Publication digest.
        digest: String,
        /// Missing witness component.
        detail: &'static str,
    },
    /// Offline exact-lock access was requested without an explicit availability trade-off.
    #[error("offline exact-lock access requires OfflinePolicy::AllowExpired")]
    OfflineExpiryRequired,
    /// The requested `SemVer` expression was invalid.
    #[error("invalid version requirement: {detail}")]
    Requirement {
        /// Parser detail.
        detail: String,
    },
    /// Cache filesystem operation failed.
    #[error("cache {operation} at {path}: {source}")]
    CacheIo {
        /// Operation being attempted.
        operation: &'static str,
        /// Path involved.
        path: PathBuf,
        /// Underlying I/O error.
        #[source]
        source: std::io::Error,
    },
}

struct Cache<'a> {
    root: &'a Path,
    limits: ClientLimits,
    tuf_limits: TufLimits,
}

impl<'a> Cache<'a> {
    fn new(root: &'a Path, limits: ClientLimits, tuf_limits: TufLimits) -> Self {
        Self {
            root,
            limits,
            tuf_limits,
        }
    }

    fn path(&self, digest: &Digest) -> PathBuf {
        let hex = digest.hex();
        self.root
            .join(digest.algorithm().as_str())
            .join(&hex[..2])
            .join(format!("{hex}.json"))
    }

    fn witness_dir(&self, digest: &Digest) -> PathBuf {
        self.path(digest).with_extension("witness")
    }

    #[allow(
        clippy::too_many_lines,
        reason = "Cache writes the record and complete authenticated witness as one flow"
    )]
    async fn write(
        &self,
        digest: &Digest,
        bytes: &[u8],
        verified: &VerifiedIndex,
        shard_bytes: &[u8],
    ) -> Result<(), Error> {
        if bytes.len() as u64 > self.limits.max_cache_entry_bytes {
            return Err(Error::CacheTooLarge {
                digest: digest.to_string(),
                size: bytes.len() as u64,
                limit: self.limits.max_cache_entry_bytes,
            });
        }
        let path = self.path(digest);
        let parent = path.parent().unwrap_or_else(|| Path::new("."));
        tokio::fs::create_dir_all(parent)
            .await
            .map_err(|source| Error::CacheIo {
                operation: "create cache directory",
                path: parent.to_owned(),
                source,
            })?;
        restrict_dir(parent)?;
        atomic_write(&path, bytes).await?;
        if shard_bytes.len() as u64 > self.limits.max_cache_entry_bytes {
            return Err(Error::CacheTooLarge {
                digest: digest.to_string(),
                size: shard_bytes.len() as u64,
                limit: self.limits.max_cache_entry_bytes,
            });
        }
        let witness = self.witness_dir(digest);
        tokio::fs::create_dir_all(&witness)
            .await
            .map_err(|source| Error::CacheIo {
                operation: "create cache witness directory",
                path: witness.clone(),
                source,
            })?;
        restrict_dir(&witness)?;
        atomic_write(&witness.join("shard.json"), shard_bytes).await?;
        let root_chain = verified.root_chain_bytes();
        let max_roots = self
            .tuf_limits
            .max_root_updates
            .checked_add(1)
            .and_then(|count| usize::try_from(count).ok())
            .unwrap_or(usize::MAX);
        if root_chain.is_empty() || root_chain.len() > max_roots {
            return Err(Error::CacheCorrupt {
                digest: digest.to_string(),
                detail: "verified root chain exceeds configured bounds".to_owned(),
            });
        }
        let max_root_bytes = self
            .tuf_limits
            .max_root_bytes
            .saturating_mul(root_chain.len() as u64);
        let mut root_bytes_total = 0u64;
        let root_chain_dir = witness.join("root-chain");
        tokio::fs::create_dir_all(&root_chain_dir)
            .await
            .map_err(|source| Error::CacheIo {
                operation: "create root-chain witness directory",
                path: root_chain_dir.clone(),
                source,
            })?;
        restrict_dir(&root_chain_dir)?;
        for (version, bytes) in &root_chain {
            root_bytes_total = root_bytes_total.saturating_add(bytes.len() as u64);
            if bytes.len() as u64 > self.tuf_limits.max_root_bytes
                || root_bytes_total > max_root_bytes
            {
                return Err(Error::CacheTooLarge {
                    digest: digest.to_string(),
                    size: root_bytes_total,
                    limit: max_root_bytes,
                });
            }
            write_witness_bounded(
                &root_chain_dir.join(format!("{version}.json")),
                bytes,
                digest,
                self.tuf_limits.max_root_bytes,
            )
            .await?;
        }
        write_witness_bounded(
            &witness.join("root.json"),
            verified.root_bytes(),
            digest,
            self.tuf_limits.max_root_bytes,
        )
        .await?;
        write_witness_optional(
            &witness.join("timestamp.json"),
            verified.timestamp_bytes(),
            digest,
            self.limits,
            "timestamp metadata",
        )
        .await?;
        write_witness_optional(
            &witness.join("snapshot.json"),
            verified.snapshot_bytes(),
            digest,
            self.limits,
            "snapshot metadata",
        )
        .await?;
        write_witness_optional(
            &witness.join("targets.json"),
            verified.targets_bytes(),
            digest,
            self.limits,
            "targets metadata",
        )
        .await
    }

    #[allow(
        clippy::too_many_lines,
        reason = "Cache read validates every witness component"
    )]
    async fn read(&self, digest: &Digest) -> Result<CachedEntry, Error> {
        let path = self.path(digest);
        let record_bytes = match tokio::fs::metadata(&path).await {
            Ok(metadata) => {
                if metadata.len() > self.limits.max_cache_entry_bytes {
                    return Err(Error::CacheTooLarge {
                        digest: digest.to_string(),
                        size: metadata.len(),
                        limit: self.limits.max_cache_entry_bytes,
                    });
                }
                tokio::fs::read(&path)
                    .await
                    .map_err(|source| Error::CacheIo {
                        operation: "read cache entry",
                        path: path.clone(),
                        source,
                    })?
            },
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => {
                return Err(Error::CacheMiss {
                    digest: digest.to_string(),
                });
            },
            Err(source) => {
                return Err(Error::CacheIo {
                    operation: "stat cache entry",
                    path,
                    source,
                });
            },
        };
        if record_bytes.len() as u64 > self.limits.max_record_bytes {
            return Err(Error::RecordTooLarge {
                digest: digest.to_string(),
                size: record_bytes.len() as u64,
                limit: self.limits.max_record_bytes,
            });
        }
        let record: PublicationRecord =
            serde_json::from_slice(&record_bytes).map_err(|source| Error::CacheCorrupt {
                digest: digest.to_string(),
                detail: source.to_string(),
            })?;
        if record.publication_digest() != digest {
            return Err(Error::CacheCorrupt {
                digest: digest.to_string(),
                detail: "record digest does not match cache key".to_owned(),
            });
        }
        let witness = self.witness_dir(digest);
        let shard_bytes = read_witness(
            &witness.join("shard.json"),
            digest,
            "identity shard",
            self.limits,
        )
        .await?;
        let root_bytes = read_witness(
            &witness.join("root.json"),
            digest,
            "root metadata",
            self.limits,
        )
        .await?;
        let root_chain = self.read_root_chain(&witness, digest).await?;
        let timestamp_bytes = read_witness(
            &witness.join("timestamp.json"),
            digest,
            "timestamp metadata",
            self.limits,
        )
        .await?;
        let snapshot_bytes = read_witness(
            &witness.join("snapshot.json"),
            digest,
            "snapshot metadata",
            self.limits,
        )
        .await?;
        let targets_bytes = read_witness(
            &witness.join("targets.json"),
            digest,
            "targets metadata",
            self.limits,
        )
        .await?;
        let snapshot = serde_json::from_slice::<tough::schema::Signed<tough::schema::Snapshot>>(
            &snapshot_bytes,
        )
        .map_err(|source| Error::CacheCorrupt {
            digest: digest.to_string(),
            detail: format!("snapshot witness is invalid: {source}"),
        })?;
        let targets =
            serde_json::from_slice::<tough::schema::Signed<tough::schema::Targets>>(&targets_bytes)
                .map_err(|source| Error::CacheCorrupt {
                    digest: digest.to_string(),
                    detail: format!("targets witness is invalid: {source}"),
                })?;
        Ok(CachedEntry {
            record_bytes,
            shard_bytes,
            root_bytes,
            root_chain,
            timestamp_bytes,
            snapshot_bytes,
            targets_bytes,
            snapshot_version: snapshot.signed.version.get(),
            targets_version: targets.signed.version.get(),
        })
    }

    async fn read_root_chain(
        &self,
        witness: &Path,
        digest: &Digest,
    ) -> Result<Vec<(u64, Vec<u8>)>, Error> {
        let directory = witness.join("root-chain");
        let mut entries = tokio::fs::read_dir(&directory).await.map_err(|source| {
            if source.kind() == std::io::ErrorKind::NotFound {
                Error::CacheWitnessMissing {
                    digest: digest.to_string(),
                    detail: "root rotation chain",
                }
            } else {
                Error::CacheIo {
                    operation: "read root-chain witness directory",
                    path: directory.clone(),
                    source,
                }
            }
        })?;
        let max_count = self
            .tuf_limits
            .max_root_updates
            .checked_add(1)
            .and_then(|count| usize::try_from(count).ok())
            .unwrap_or(usize::MAX);
        let max_bytes = self
            .tuf_limits
            .max_root_bytes
            .saturating_mul(max_count as u64);
        let mut roots = Vec::new();
        let mut total = 0u64;
        while let Some(entry) = entries
            .next_entry()
            .await
            .map_err(|source| Error::CacheIo {
                operation: "iterate root-chain witness directory",
                path: directory.clone(),
                source,
            })?
        {
            if roots.len() >= max_count {
                return Err(Error::CacheTooLarge {
                    digest: digest.to_string(),
                    size: (roots.len() as u64).saturating_add(1),
                    limit: max_count as u64,
                });
            }
            let file_type = entry.file_type().await.map_err(|source| Error::CacheIo {
                operation: "inspect root-chain witness entry",
                path: entry.path(),
                source,
            })?;
            if !file_type.is_file() {
                return Err(Error::CacheCorrupt {
                    digest: digest.to_string(),
                    detail: "root-chain witness contains a non-file entry".to_owned(),
                });
            }
            let name = entry.file_name();
            let name = name.to_str().ok_or_else(|| Error::CacheCorrupt {
                digest: digest.to_string(),
                detail: "root-chain witness filename is not UTF-8".to_owned(),
            })?;
            let version = name
                .strip_suffix(".json")
                .filter(|value| !value.is_empty())
                .and_then(|value| value.parse::<u64>().ok())
                .ok_or_else(|| Error::CacheCorrupt {
                    digest: digest.to_string(),
                    detail: format!("invalid root-chain witness filename {name:?}"),
                })?;
            let bytes = read_witness_bounded(
                &entry.path(),
                digest,
                "root rotation chain",
                self.tuf_limits.max_root_bytes,
            )
            .await?;
            total = total.saturating_add(bytes.len() as u64);
            if total > max_bytes {
                return Err(Error::CacheTooLarge {
                    digest: digest.to_string(),
                    size: total,
                    limit: max_bytes,
                });
            }
            roots.push((version, bytes));
        }
        roots.sort_by_key(|(version, _)| *version);
        if roots.windows(2).any(|pair| pair[0].0 == pair[1].0) {
            return Err(Error::CacheCorrupt {
                digest: digest.to_string(),
                detail: "root-chain witness contains duplicate versions".to_owned(),
            });
        }
        Ok(roots)
    }
}

async fn write_witness_bytes(
    path: &Path,
    bytes: &[u8],
    digest: &Digest,
    limits: ClientLimits,
) -> Result<(), Error> {
    if bytes.len() as u64 > limits.max_cache_entry_bytes {
        return Err(Error::CacheTooLarge {
            digest: digest.to_string(),
            size: bytes.len() as u64,
            limit: limits.max_cache_entry_bytes,
        });
    }
    atomic_write(path, bytes).await
}

async fn write_witness_bounded(
    path: &Path,
    bytes: &[u8],
    digest: &Digest,
    limit: u64,
) -> Result<(), Error> {
    if bytes.len() as u64 > limit {
        return Err(Error::CacheTooLarge {
            digest: digest.to_string(),
            size: bytes.len() as u64,
            limit,
        });
    }
    atomic_write(path, bytes).await
}

async fn write_witness_optional(
    path: &Path,
    bytes: Option<&[u8]>,
    digest: &Digest,
    limits: ClientLimits,
    detail: &'static str,
) -> Result<(), Error> {
    let bytes = bytes.ok_or_else(|| Error::CacheWitnessMissing {
        digest: digest.to_string(),
        detail,
    })?;
    write_witness_bytes(path, bytes, digest, limits).await
}

async fn read_witness(
    path: &Path,
    digest: &Digest,
    detail: &'static str,
    limits: ClientLimits,
) -> Result<Vec<u8>, Error> {
    read_witness_bounded(path, digest, detail, limits.max_cache_entry_bytes).await
}

async fn read_witness_bounded(
    path: &Path,
    digest: &Digest,
    detail: &'static str,
    limit: u64,
) -> Result<Vec<u8>, Error> {
    let metadata = tokio::fs::metadata(path).await.map_err(|source| {
        if source.kind() == std::io::ErrorKind::NotFound {
            Error::CacheWitnessMissing {
                digest: digest.to_string(),
                detail,
            }
        } else {
            Error::CacheIo {
                operation: "stat cache witness",
                path: path.to_owned(),
                source,
            }
        }
    })?;
    if metadata.len() > limit {
        return Err(Error::CacheTooLarge {
            digest: digest.to_string(),
            size: metadata.len(),
            limit,
        });
    }
    tokio::fs::read(path)
        .await
        .map_err(|source| Error::CacheIo {
            operation: "read cache witness",
            path: path.to_owned(),
            source,
        })
}

async fn atomic_write(path: &Path, bytes: &[u8]) -> Result<(), Error> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    let temp = parent.join(format!(
        ".{}.{}.tmp",
        path.file_name().unwrap_or_default().to_string_lossy(),
        uuid::Uuid::new_v4()
    ));
    let mut options = tokio::fs::OpenOptions::new();
    options.create_new(true).write(true);
    #[cfg(unix)]
    options.mode(0o600);
    let write_result = async {
        let mut file = options.open(&temp).await?;
        file.write_all(bytes).await?;
        file.sync_all().await
    }
    .await;
    if let Err(source) = write_result {
        let _ = tokio::fs::remove_file(&temp).await;
        return Err(Error::CacheIo {
            operation: "write cache temporary entry",
            path: temp,
            source,
        });
    }
    if let Err(source) = tokio::fs::rename(&temp, path).await {
        let _ = tokio::fs::remove_file(&temp).await;
        return Err(Error::CacheIo {
            operation: "commit cache entry",
            path: path.to_owned(),
            source,
        });
    }
    #[cfg(unix)]
    {
        std::fs::File::open(parent)
            .and_then(|directory| directory.sync_all())
            .map_err(|source| Error::CacheIo {
                operation: "sync cache directory",
                path: parent.to_owned(),
                source,
            })?;
    }
    Ok(())
}

fn restrict_dir(path: &Path) -> Result<(), Error> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o700)).map_err(
            |source| Error::CacheIo {
                operation: "restrict cache directory",
                path: path.to_owned(),
                source,
            },
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests;
